all:
  hosts:
    k8s-master-0:
      ansible_host: 10.11.12.148
      ip: 10.11.12.148
      access_ip: 10.11.12.148
    k8s-worker-0 :
      ansible_host: 10.11.12.118
      ip: 10.11.12.118
      access_ip: 10.11.12.118
    k8s-worker-1:
      ansible_host: 10.11.12.96
      ip: 10.11.12.96
      access_ip: 10.11.12.96
  children:
    kube_control_plane:
      hosts:
        k8s-master-0:
    kube_node:
      hosts:
        k8s-master-0:
        k8s-worker-0 :
        k8s-worker-1:
    etcd:
      hosts:
        k8s-master-0:
        k8s-worker-0 :
        k8s-worker-1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
    bastion:
      hosts:
        bastion:
          ansible_host: 195.15.193.67 
          ansible_user: ubuntu
